server:
  port: 8001
spring:
  application:
    name: spring-cloud-config-server
#  profiles:
#    active: native   #我们只需要设置属性spring.profiles.active=native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yaoxu07/Spring-Cloud.git    # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                             # git仓库的账号
          password:                                             # git仓库的密码
Spring:
  cloud:
    config:
      server:
        native:
          searchLocations=file: E:\1、Spring-learn\6、SpringCloudDemoForGIT\SpringCloud-ItUKonw/properties/
 #也可以通过spring.cloud.config.server.native.searchLocations=file:E:/properties/属性来指定配置文件的位置。虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。